// Generated by CoffeeScript 1.6.3
(function() {
  var Dynasty, Q, Table, aws, debug, lib, typeToAwsType, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  aws = require('./lib/aws');

  _ = require('lodash');

  Q = require('q');

  debug = require('debug')('dynasty');

  Q.longStackSupport = true;

  typeToAwsType = {
    string: 'S',
    string_set: 'SS',
    number: 'N',
    number_set: 'NS',
    binary: 'B',
    binary_set: 'BS'
  };

  lib = require('./lib');

  Table = lib.Table;

  Dynasty = (function() {
    function Dynasty(credentials) {
      this.redescribeTables = __bind(this.redescribeTables, this);
      this.loadAllTables = __bind(this.loadAllTables, this);
      debug("dynasty constructed.");
      credentials.region = credentials.region || 'us-east-1';
      credentials.apiVersion = '2012-08-10';
      this.execute = aws(credentials);
      this.name = 'Dynasty';
      this.tables = {};
    }

    Dynasty.prototype.loadAllTables = function() {
      var deferred,
        _this = this;
      deferred = Q.defer();
      this.list()["catch"](deferred.reject).done(function(data) {
        var table, tableName, tablesKeyed, _i, _len, _ref;
        tablesKeyed = [];
        _ref = data.TableNames;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tableName = _ref[_i];
          table = _this.table(tableName);
          tablesKeyed.push(table.key);
        }
        return Q.all(tablesKeyed).done(function() {
          return deferred.resolve(_this.tables);
        });
      });
      return deferred.promise;
    };

    Dynasty.prototype.redescribeTables = function() {
      var allTablesDescribed, name, table, _ref;
      allTablesDescribed = [];
      _ref = this.tables;
      for (name in _ref) {
        table = _ref[name];
        allTablesDescribed.push(table.updateDescription());
      }
      return Q.all(allTablesDescribed);
    };

    Dynasty.prototype.table = function(name) {
      return this.tables[name] = this.tables[name] || new Table(this, name);
    };

    /*
    Table Operations
    */


    Dynasty.prototype.alter = function(name, params, callback) {
      var awsParams, promise, throughput;
      debug("alter() - " + name + ", " + params);
      throughput = params.throughput || params;
      awsParams = {
        TableName: name,
        ProvisionedThroughput: {
          ReadCapacityUnits: throughput.read,
          WriteCapacityUnits: throughput.write
        }
      };
      promise = this.execute('UpdateTable', awsParams);
      if (callback === !null) {
        promise = promise.nodeify(callback);
      }
      return promise;
    };

    Dynasty.prototype.create = function(name, params, callback) {
      var attributeDefinitions, awsParams, keySchema, promise, throughput;
      if (callback == null) {
        callback = null;
      }
      debug("create() - " + name + ", " + params);
      throughput = params.throughput || {
        read: 10,
        write: 5
      };
      keySchema = [
        {
          KeyType: 'HASH',
          AttributeName: params.key_schema.hash[0]
        }
      ];
      attributeDefinitions = [
        {
          AttributeName: params.key_schema.hash[0],
          AttributeType: typeToAwsType[params.key_schema.hash[1]]
        }
      ];
      awsParams = {
        AttributeDefinitions: attributeDefinitions,
        TableName: name,
        KeySchema: keySchema,
        ProvisionedThroughput: {
          ReadCapacityUnits: throughput.read,
          WriteCapacityUnits: throughput.write
        }
      };
      promise = this.execute('CreateTable', awsParams);
      if (callback === !null) {
        promise = promise.nodeify(callback);
      }
      return promise;
    };

    Dynasty.prototype.describe = function(name, callback) {
      var promise;
      if (callback == null) {
        callback = null;
      }
      debug("describe() - " + name);
      promise = this.execute('DescribeTable', {
        TableName: name
      });
      if (callback === !null) {
        promise = promise.nodeify(callback);
      }
      return promise;
    };

    Dynasty.prototype.drop = function(name, callback) {
      var params, promise;
      if (callback == null) {
        callback = null;
      }
      debug("drop() - " + name);
      params = {
        TableName: name
      };
      promise = this.execute('DeleteTable', params);
      if (callback === !null) {
        promise = promise.nodeify(callback);
      }
      return promise;
    };

    Dynasty.prototype.list = function(params, callback) {
      var awsParams, promise;
      debug("list() - " + params);
      awsParams = {};
      if (params === !null) {
        if (_.isString(params)) {
          awsParams.ExclusiveStartTableName = params;
        } else if (_.isFunction(params)) {
          callback = params;
        } else if (_.isObject(params)) {
          if (params.limit === !null) {
            awsParams.Limit = params.limit;
          } else if (params.start === !null) {
            awsParams.ExclusiveStartTableName = params.start;
          }
        }
      }
      promise = this.execute('ListTables', awsParams);
      if (callback === !null) {
        promise = promise.nodeify(callback);
      }
      return promise;
    };

    return Dynasty;

  })();

  module.exports = function(credentials) {
    return new Dynasty(credentials);
  };

}).call(this);
